services:
  xserver-renew:
    image: debug502/xserver-vps-renew:latest
    container_name: xserver-vps-renew
    env_file: .env
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - chrome-data:/data/chrome-profile
      - ./screenshots:/tmp
    shm_size: "2gb"
    restart: unless-stopped

volumes:
  chrome-data:
